**NumPy库和pandas库主要用于处理一维及二维的表格数据，而Matplotlib库是数据可视化的工具。**

# 一、NumPy库

NumPy库的主要特点是引入了数组的概念

In [8]:
import warnings
warnings.filterwarnings("ignore") # 忽略警告信息，不影响代码执行

import numpy as np
a = [1, 2, 3, 4] #创建列表 a  
b = np.array([1, 2, 3, 4]) # 创建数组
print(a)
print(b)
print(type(a))
print(type(b))

[1, 2, 3, 4]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [4]:
# 通过索引和切片访问列表和数组中的元素
print(a[1])
print(b[1])
print(a[0:2]) # 列表切片“左闭右开”
print(b[0:2]) # 数组切片“左闭右开”

2
2
[1, 2]
[1 2]


### 数组和列表的区别
从上述输出结果可以看出，列表和数组有着相同的索引机制，唯一的区别就是数组中的元素通过空格分隔，而列表中的元素通过逗号分隔。

第一，NumPy作为一个专门用于数据处理的库，能很好地支持一些数学运算，而用列表进行数学运算则较为麻烦，如下

In [5]:
c = a * 2
d = b * 2
print(c)
print(d)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


列表是把元素复制了一遍，而数组则是对每个元素做了乘法。

第二，列表存储的是一维数据，而数组则能存储多维数据。

In [6]:
e = [[1,2], [3,4], [5,6]] # 列表里的元素为小列表
f = np.array([[1,2], [3,4], [5,6]]) # 创建二维数组
print(e)
print('--------')
print(f) # 数据处理中经常用到二维数组，即二维的表格结构

[[1, 2], [3, 4], [5, 6]]
--------
[[1 2]
 [3 4]
 [5 6]]


### 创建数组的几种方式

In [13]:
b = np.array([1, 2, 3, 4]) # 创建一维数组
f = np.array([[1,2], [3, 4], [5, 6]]) #创建二维数组
print(b)
print('--------')
print(f)

[1 2 3 4]
--------
[[1 2]
 [3 4]
 [5 6]]


In [14]:
# 一个参数 参数值为终点，起点取默认值0，步长取默认值1
x = np.arange(5)
# 两个参数 第一个参数为起点，第二个参数为终点，步长取默认值1，左闭右开
y = np.arange(5,10)
# 三个参数 第一个参数为起点，第二个参数为终点，第三个参数为步长，左闭右开
z = np.arange(5, 10, 0.5)
print(x)
print(y)
print(z)

[0 1 2 3 4]
[5 6 7 8 9]
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [18]:
# 通过np.random模块来创建随机一维数组，比如可以通过np.random.randn(3)来创建一个服从正太分布（均值为0，方差为1的分布）的3个随机数一维数组
a = np.random.randn(3)
print(a)

[1.3647155  0.11332937 1.52294573]


In [25]:
#把np.random.randn(3)换成np.random.rand(3)，那生成的就是0-1之间的3个随机数
a = np.random.rand(3)
print(a)

[0.47616928 0.26968447 0.3530244 ]


In [15]:
# 创建随机二维数组，# 创建随机一维数组
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
# np.random.randint()函数用于创建随机整数，括号里第1个参数0为起始数，第2个参数10为终止数，第3个参数（4,4）则表示创建一个4行4列的二维数组
a = np.random.randint(0, 10, (4,4))
print(a)

[[3 9 4 5]
 [6 0 4 2]
 [6 6 4 7]
 [2 3 2 2]]
